# Generated by Django 2.2.12 on 2020-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='article',
            name='up_num',
        ),
        migrations.AddField(
            model_name='article',
            name='introduce',
            field=models.CharField(default='', max_length=90, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=90, verbose_name='文章标题'),
        ),
    ]
