# Generated by Django 2.2.12 on 2020-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200807_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='introduce',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(default='', upload_to='content', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
    ]
