# Generated by Django 2.2.12 on 2020-08-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200807_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titile',
            field=models.CharField(default='', max_length=30, verbose_name='标题'),
        ),
    ]
