# Generated by Django 2.2.12 on 2020-08-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20200808_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_up',
            field=models.BooleanField(default=False, verbose_name='已点赞'),
        ),
    ]
