# Generated by Django 2.2.12 on 2020-08-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_article_is_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
