# Generated by Django 2.2.12 on 2020-08-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_up',
        ),
    ]
