# Generated by Django 2.2.12 on 2020-08-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0004_auto_20200824_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='大订单号')),
                ('odate', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('oIsPay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('ototal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('oaddress', models.CharField(max_length=150, verbose_name='订单地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='订单用户')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='所属商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.OrderInfo', verbose_name='商品所属订单')),
            ],
            options={
                'verbose_name': '订单跟商品关系表',
                'verbose_name_plural': '订单跟商品关系表',
            },
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
