# Generated by Django 2.2.12 on 2020-08-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('gander', models.CharField(max_length=11, verbose_name='性别')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('birthday_day', models.CharField(max_length=20, verbose_name='出生日期')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
