# Generated by Django 2.2.12 on 2020-08-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='hello.png', upload_to='avatar', verbose_name='头像'),
        ),
    ]
