# Generated by Django 2.2.12 on 2020-08-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200808_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gander',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='0', max_length=11, verbose_name='性别'),
        ),
    ]
