# Generated by Django 2.2.12 on 2020-08-24 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0003_auto_20200819_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'vip0'), (1, 'vip1'), (2, 'vip2'), (3, 'vip3'), (4, 'vip4'), (5, 'vip5'), (6, 'vip6'), (7, 'vip7'), (8, 'vip8'), (9, 'vip9'), (10, 'vip10')], default=0, verbose_name='会员等级')),
                ('integrals', models.CharField(default=0, max_length=50, verbose_name='总积分')),
                ('ava_int', models.CharField(default=10, max_length=50, verbose_name='可用积分')),
                ('discounts', models.CharField(default=10, max_length=50, verbose_name='优惠折扣')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='浏览时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户浏览记录',
                'verbose_name_plural': '用户浏览记录',
            },
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='所在地区')),
                ('addr', models.CharField(max_length=100, verbose_name='收货地址')),
                ('name', models.CharField(max_length=30, verbose_name='收货人')),
                ('postcode', models.CharField(default='', max_length=6, verbose_name='邮编')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户ID')),
            ],
        ),
    ]
